Repository UBC-MDS/dsresumatch, pull requests merged in 2025-01, with the labels that each got.

#13 Created function docs for reading and cleaning the text
  src/dsresumatch/pdf_cv_processing.py
Labels: function

#14 added sections_check functions skeleton
  src/dsresumatch/dsresumatch.py
  src/dsresumatch/sections_check.py
Labels: function

#17 added function skeleton and docstring for resume_score
  src/dsresumatch/resume_scoring.py
Labels: function

#18 updated ReadMe and Contributing with our function information
  CONTRIBUTING.md
  README.md
Labels: documentation

#22 Updated section_checks function optional arguments
  README.md
Labels: documentation

#39 Implemented missing_section function
  README.md
  src/dsresumatch/sections_check.py
  tests/conftest.py
  tests/test_missing_section.py
Labels: function, test

#43 Merge main into feature/resume_score
  CONTRIBUTING.md
  README.md
  poetry.lock
  pyproject.toml
  src/dsresumatch/data/baseline_keywords.json
  src/dsresumatch/evaluate_keywords.py
  src/dsresumatch/pdf_cv_processing.py
  src/dsresumatch/sections_check.py
  tests/conftest.py
  tests/dummy.pdf
  tests/empty.pdf
  tests/test_dsresumatch.py
  tests/test_evaluate_keywords.py
  tests/test_missing_section.py
  tests/test_pdf_cv_processing.py
Labels: function

#44 Feature/resume score
  CONTRIBUTING.md
  src/dsresumatch/resume_scoring.py
  tests/test_evaluate_keywords.py
  tests/test_resume_scoring.py
Labels: function

#51 Added pytest-cov extension as development dependency
  poetry.lock
  pyproject.toml
Labels: chore

#56 Added missing_section tutorial examples
  docs/example.ipynb
Labels: documentation

#59 Doc/tutorial
  docs/example.ipynb
  poetry.lock
  pyproject.toml
  src/dsresumatch/resume_scoring.py
Labels: documentation

#60 changed theme to furo in conf.py
  docs/conf.py
Labels: bug

#64 added readthedocs and codecov badges to README.md
  README.md
Labels: documentation

#70 Updated GITHUB_TOKEN to RELEASE_TOKEN
  .github/workflows/ci-cd.yml
Labels: chore

#72 Added token for checkout user
  .github/workflows/ci-cd.yml
Labels: bug

#81 fix: Feedback from Milestone 2.
  tests/test_evaluate_keywords.py
Labels: test

#84 fix: Feedback for missing_section tests documentation
  tests/test_missing_section.py
Labels: enhancement

#91 Fix/readme
  README.md
Labels: enhancement
